### ISSUE TITLE
ประชุมครั้งที่1 :  บรีฟงานกันนน 🧸

### ISSUE THREAD

**Issue by cnc2003** [uoqq/G1-06-Workhard#17]
เพื่อนๆเราเริ่มนัดงานกันเลยมั้ยอะ :D

**Comment by cnc2003** [comment]
เพื่อนๆเราเริ่มนัดงานกันเลยมั้ยอะ  :D

**Comment by OParnu** [comment]
**เริ่มเลยครับ**
เราว่าเริ่มจากการแบ่งหัวข้อของงานดีมั้ย ว่าในงานนี้มีหัวข้ออะไรบ้าง

**Comment by findmelily** [comment]
ถ้าหัวข้อของงานก็มี
> ใส่บทสัมภาษณ์ของก้อง (say do think feel)
> ใส่ journey map ที่ทำในห้อง
> หา need กับ insight
> เขียน pov ของตัวเอง
> สรุป feedback ของเพื่อนๆเพื่อไปปรับปรุง
((ถ้าขาดอะไร เพื่อนทักได้นะ))

**Comment by findmelily** [comment]
นัดกันทำวันอังคารไหมม เห็นเพื่อนไม่ว่างอาทิตย์กับจันทร์

**Comment by cnc2003** [comment]
> นัดกันทำวันอังคารไหมม เห็นเพื่อนไม่ว่างอาทิตย์กับจันทร์

ได้โอเครเลย งั้นเรามาเตรียมข้อมูลก่อนเลยมั้ย

**Comment by OParnu** [comment]
ได้เลยครับ มาเตรียมข้อมูลกัน

**Comment by cnc2003** [comment]
เราคิดว่าข้อมูลที่ได้มาเราต้องสัมภาษณ์เพิ่มเติมให้มันครอบคลุมกว่าเดิมนะ

**Comment by Jhatniphat** [comment]
เดี๋ยวเราจะต้องช่วยกันคัดเลือก feedback ด้วย

**Comment by cnc2003** [comment]
เรานัดสัมภาษณ์กันวันอังคารดีมั้ย

**Comment by OParnu** [comment]
ได้เลย เป็นวันอังคารละกัน จะได้รู้งานพร้อมๆกันด้วย 👍

**Comment by Jhatniphat** [comment]
วันอังคารก็ดีเลย ทุกคนว่างพอดี

**Comment by findmelily** [comment]
งั้นสรุป เรามาสัมภาษณ์เพิ่มเติมวันอังคารนะ ถ้ามีไรเพิ่มเติมเดี๋ยวจะแจ้งใหม่
