### ISSUE TITLE
ประชุมครั้งที่2 : แบ่งงานน

### ISSUE THREAD

**Issue by uoqq** [uoqq/G1-06-Workhard#19]
??

**Comment by cnc2003** [comment]
เราจะแบ่งงานกันตามนี้นะ
- what how why 
- say do think feel , journey map
- need insight
- pov
- feedback (i wish/i like)

**Comment by uoqq** [comment]
เราเอา feedback (i wish/i like)

**Comment by OParnu** [comment]
เราทำ journey map นะ

**Comment by findmelily** [comment]
เดี๋ยวทำ say do think feel ให้

**Comment by Jhatniphat** [comment]
เดี๋ยวทำ what how why ให้

**Comment by BookCnk** [comment]
เด่วเราทำ Pov น่ะเพื่่อน

**Comment by cnc2003** [comment]
งั้นเดี๋ยวบูมทำส่วนของ question กับ need insight ให้นะทุกคนน

**Comment by cnc2003** [comment]
สรุปหน้าที่แบ่งงาน
- คำถามระหว่างสัมภาษณ์ | บูม
- what how why | อั้ม
- say do think feel | พิณ
- journey map | โอม
- need insight | บูม
- pov | บุ๊ค
- feedback (i wish/i like) | ก้อง
