### ISSUE TITLE
เพื่อนๆ มีคำถามสัมภาษณ์อะไรบ้าง

### ISSUE THREAD

**Issue by findmelily** [uoqq/G1-06-Workhard#33]
มาแชร์คำถามสัมภาษณ์กัน

**Comment by uoqq** [comment]
เวลาปกติเค้านอนกันท่าไหนน ??

**Comment by Jhatniphat** [comment]
คิดว่าอาชีพมีผลต่อการนอนของตนไหม

**Comment by OParnu** [comment]
1.เข้านอน-ตื่นกี่โมง
2.ตื่นกลางดึกบ้างมั้ย
3.โดยรวมแล้วนอนวันละกี่ชั่วโมง

**Comment by uoqq** [comment]
มีปัญหาด้านการนอนรึป่าว

**Comment by uoqq** [comment]
คิดว่าอาชีพมีผลต่อการนอนของตนเองไหม

**Comment by uoqq** [comment]
คิดว่าอะไรที่มีผลต่อการนอนหลับ

**Comment by uoqq** [comment]
มีโรคประจําตัวรึป่าว ??

**Comment by uoqq** [comment]
สรุป
(User persona)
1. อายุเท่าไร
2. ปัจจุบันทำงานอาชีพอะไร (ไม่บังคับถาม)
3. ปัจจุบันอยู่อาศัยกันกี่คน
4. กิจกรรมยามว่าง
5. อาหารชอบ ชอบทานไรจ๊ะ
6. มีความสนใจในเรื่องไหนมากที่สุด


 Q-A
(ให้เล่าชีวิตประจำวันด้วย)
 เวลา
1. โดยรวมแล้วนอนวันละกี่ชั่วโมง
2. เข้านอน-ตื่นกี่โมง
3. ตื่นกลางดึกบ้างมั้ย

พฤติกรรม
1. เวลานอนนอนท่าไหน
2. ปกตินอนกลางวันด้วยไหม
3. กิจกรรมก่อนนอนได้ทำอะไรบ้าง
4. ปกติแล้วได้ออกกําลังกายบ่อยมั้ย

การดื่ม การกิน
1. กินก่อนนอนไหม
2. ดื่มกาแฟไหม
3. จริงหรือที่อาหารบางอย่างช่วยทำให้หลับได้ดีขึ้น
4. ดื่มแอลกอฮอลล์หรือเปล่า

 ปัจจัย
1. มีปัญหาด้านการนอนไหม
    1. เป็นปัญหาขนาดไหน
    2. อย่างไร
    3. ยกตัวอย่างได้ไหม
2. ปกติแล้วแก้ปัญหายังไง
    1. ทำไมทำอย่างนั้น
    2. คิดว่าเป็นวิธีที่แก้ปัญหาที่ดีที่สุดแล้วมั้ย
    3. เป็นไปได้อยากให้แก้ปัญหายังไง
3. คิดว่าอาชีพมีผลต่อการนอนของตนไหม
4. คิดว่าอะไรที่มีผลต่อการนอนหลับ
5. มีโรคประจำตัวไหม
