### ISSUE TITLE
แบ่งงานกัน

### ISSUE THREAD

**Issue by findmelily** [uoqq/G1-06-Workhard#34]
เราคิดว่าในตอนนี้จะแบ่งงาน 6 หัวข้อให้แต่ละคนเขียนตามนี้ (แบ่งงานให้แต่คนเขียนเฉยๆ คิดจะคิดด้วยกัน)
- What-how-why
- say-do-think-feel
- Journey map
- User persona
- Identified insights
- PoV statement
เพื่อนจองเลยใครจะทำอะไร

**Comment by Jhatniphat** [comment]
เดี๋ยวทำ User persona ให้ค้าบ

**Comment by uoqq** [comment]
เดี๋ยวทํา say-do-think-feel ให้ๆ

**Comment by BookCnk** [comment]
เดี๋ยวเราทํา PoV statement

**Comment by findmelily** [comment]
ฉันทำ insights นะ

**Comment by cnc2003** [comment]
บูมทำ journey map ละกันนน

**Comment by findmelily** [comment]
สรุปนะ

What-how-why โอม
say-do-think-feel ก้อง
Journey map บูม
User persona อั้ม
Identified insights พิณ
PoV statement บุ๊ค
